---
title: Perturbation of Neoclassical Model
author: Pablo Winant
format:
  html: default
  ipynb: default
jupyter: julia-1.12
execute: 
  enabled: false
---

Our goal here is to compute a linear approximation of solution to the neoclassical model, c#   execute:
#   freeze: true  
# execute: 
#   enabled: falselose ot the steady-state.

@. __Warm-up: install the `ForwardDiff` library. Use it to differentiate the function below. Check the jacobian function.__

Note: the signature of function `f` needs to be fixed first to allow for dual numbers as arguments.

```{julia}
# function f(x::Vector{T}) where T <: Number
function f(x)
    a = x[1]
    b = x[2]
    x1 = a+b
    x2 = a*exp(b)
    return [x1,x2]
end
```

```{julia}
# your code here
```

@. __Create a NamedTuple to hold the model parameters.__

```{julia}
# your code here
```


@. __Define two functions:__

- `transition(z::Number, k::Number, i::Number, p)::Tuple{Number}` which returns productivity and capital at date `t+1` as a function of productivity, capital and investment at date `t`

- `arbitrage(z::Number, k::Number, i::Number, Z::Number, K::Number, I::Number, p)::Number` which returns the residual of the euler equation (lower case variable for date t, upper case for date t+1)

```{julia}

```

```{julia}

```

@. __Using multiple dispatch, define two variants of the same functions, that take vectors as input and output arguments:__

- `arbitrage(s::Vector{T}, x::Vector{T}, S::Vector{T}, X::Vector{T}, p) where T<:Number`
- `transition(s::Vector{T}, x::Vector{T}, p) where T<:Number`

```{julia}
# your code here
```

```{julia}
# your code here
```

```{julia}
# your code here
```

@. __Write a function `steady_state(p)::Tuple{Vector,Vector}` which computes the steady-state of the model computed by hand.__
It returns two vectors, one for the states, one for the controls. Check that the steady-state satisfies the model equations.

```{julia}
# your code here
```

```{julia}
# your code here
```

The first order system satisfies:
$$\begin{align}A s_t + B x_t + C s_{t+1} + D x_{t+1} & = & 0 \\\\ 
s_{t+1} & = & E s_t + F x_t
 \end{align}$$

@. __Define a structure `PerturbedModel` to hold matrices A,B,C,D,E,F.__

```{julia}
# your code here
```


@. __Write a function `first_order_model(s::Vector, x::Vector, p)::PerturbedModel`, which returns the first order model, given the steady-state and the calibration. Suggestion: use `ForwardDiff.jl` library.__

```{julia}
# your code here
```


2. __We look for a linear solution $x_t = X s_t$ . Write the matrix equation which `X` must satisfy. Write a function `residual(X::Array, M::PerturbedModel)` which computes the residual of this equation for a given `X`.__

```{julia}
# your code here
```

@. __Write a function `T(X, M::PerturbedModel)`  which implements the time iteration step.__

```{julia}
# your code here
```

@. __Write function `linear_time_iteration(X_0::Matrix, m::PerturbedModel)::Matrix` which implements the time iteration algorithm. Apply it to `X0 = rand(1,2)` and check that the result satisfies the first order model.__


```{julia}
# your code here
```

@. __Check blanchard Kahn Conditions__

```{julia}
# your code here
```


@. __Write a function `simulate(s0::Vector, X::Matrix, p, T::Int64)::Tuple{Matrix, Matrix}` to simulate the model over $T$ periods (by using the formula $\Delta s_t = (E + F X) \Delta s_{t-1})$. Return a matrix for the states (one line per date) and another matrix for the controls. Bonus: add a keyword option to compute variables levels or log-deviations. If possible, return a DataFrame object.__


```{julia}
# your code here
```

@. __Make some nice plots.__


```{julia}

```